// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0UDlC4ARWe3kZpW6BAadXJupeRfR-GVk',
    appId: '1:437532687849:web:e37259ce5f01b0dffb1f78',
    messagingSenderId: '437532687849',
    projectId: 'to-do-app-d2fc6',
    authDomain: 'to-do-app-d2fc6.firebaseapp.com',
    storageBucket: 'to-do-app-d2fc6.appspot.com',
    measurementId: 'G-YW2PZK0QNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh89-zmcYlpmIBmBR6k9I8toJ6DUYtAPw',
    appId: '1:437532687849:android:b1680c74f2644059fb1f78',
    messagingSenderId: '437532687849',
    projectId: 'to-do-app-d2fc6',
    storageBucket: 'to-do-app-d2fc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASE8AGD1slwPkj-QOX2SJ7XdCFpUJIcOk',
    appId: '1:437532687849:ios:dbed16da752d00c4fb1f78',
    messagingSenderId: '437532687849',
    projectId: 'to-do-app-d2fc6',
    storageBucket: 'to-do-app-d2fc6.appspot.com',
    iosClientId: '437532687849-8m2kkda7jldm5v08n87dsd7husuvq0um.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASE8AGD1slwPkj-QOX2SJ7XdCFpUJIcOk',
    appId: '1:437532687849:ios:37fad74b7dded80cfb1f78',
    messagingSenderId: '437532687849',
    projectId: 'to-do-app-d2fc6',
    storageBucket: 'to-do-app-d2fc6.appspot.com',
    iosClientId: '437532687849-9ijfvm9gd0pq3s6514uujjroeijki9e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
